sbatch --out=slurm/horizon/trial_4_1_2_3__use_centroids.out --err=slurm/horizon/trial_4_1_2_3__use_centroids.err runpymain.sh horizon.py --step 4 --n_rows 2 --kernel_size 3 --use_centroids --src_dir input_1 --output_dir output_1_4_1_2_3__use_centroids
sbatch --out=slurm/horizon/trial_4_1_2_3_.out --err=slurm/horizon/trial_4_1_2_3_.err runpymain.sh horizon.py --step 4 --n_rows 2 --kernel_size 3  --src_dir input_1 --output_dir output_1_4_1_2_3_
sbatch --out=slurm/horizon/trial_4_1_2_5__use_centroids.out --err=slurm/horizon/trial_4_1_2_5__use_centroids.err runpymain.sh horizon.py --step 4 --n_rows 2 --kernel_size 5 --use_centroids --src_dir input_1 --output_dir output_1_4_1_2_5__use_centroids
sbatch --out=slurm/horizon/trial_4_1_2_5_.out --err=slurm/horizon/trial_4_1_2_5_.err runpymain.sh horizon.py --step 4 --n_rows 2 --kernel_size 5  --src_dir input_1 --output_dir output_1_4_1_2_5_
sbatch --out=slurm/horizon/trial_4_1_2_7__use_centroids.out --err=slurm/horizon/trial_4_1_2_7__use_centroids.err runpymain.sh horizon.py --step 4 --n_rows 2 --kernel_size 7 --use_centroids --src_dir input_1 --output_dir output_1_4_1_2_7__use_centroids
sbatch --out=slurm/horizon/trial_4_1_2_7_.out --err=slurm/horizon/trial_4_1_2_7_.err runpymain.sh horizon.py --step 4 --n_rows 2 --kernel_size 7  --src_dir input_1 --output_dir output_1_4_1_2_7_
sbatch --out=slurm/horizon/trial_4_1_4_3__use_centroids.out --err=slurm/horizon/trial_4_1_4_3__use_centroids.err runpymain.sh horizon.py --step 4 --n_rows 4 --kernel_size 3 --use_centroids --src_dir input_1 --output_dir output_1_4_1_4_3__use_centroids
sbatch --out=slurm/horizon/trial_4_1_4_3_.out --err=slurm/horizon/trial_4_1_4_3_.err runpymain.sh horizon.py --step 4 --n_rows 4 --kernel_size 3  --src_dir input_1 --output_dir output_1_4_1_4_3_
sbatch --out=slurm/horizon/trial_4_1_4_5__use_centroids.out --err=slurm/horizon/trial_4_1_4_5__use_centroids.err runpymain.sh horizon.py --step 4 --n_rows 4 --kernel_size 5 --use_centroids --src_dir input_1 --output_dir output_1_4_1_4_5__use_centroids
sbatch --out=slurm/horizon/trial_4_1_4_5_.out --err=slurm/horizon/trial_4_1_4_5_.err runpymain.sh horizon.py --step 4 --n_rows 4 --kernel_size 5  --src_dir input_1 --output_dir output_1_4_1_4_5_
sbatch --out=slurm/horizon/trial_4_1_4_7__use_centroids.out --err=slurm/horizon/trial_4_1_4_7__use_centroids.err runpymain.sh horizon.py --step 4 --n_rows 4 --kernel_size 7 --use_centroids --src_dir input_1 --output_dir output_1_4_1_4_7__use_centroids
sbatch --out=slurm/horizon/trial_4_1_4_7_.out --err=slurm/horizon/trial_4_1_4_7_.err runpymain.sh horizon.py --step 4 --n_rows 4 --kernel_size 7  --src_dir input_1 --output_dir output_1_4_1_4_7_
sbatch --out=slurm/horizon/trial_4_1_8_3__use_centroids.out --err=slurm/horizon/trial_4_1_8_3__use_centroids.err runpymain.sh horizon.py --step 4 --n_rows 8 --kernel_size 3 --use_centroids --src_dir input_1 --output_dir output_1_4_1_8_3__use_centroids
sbatch --out=slurm/horizon/trial_4_1_8_3_.out --err=slurm/horizon/trial_4_1_8_3_.err runpymain.sh horizon.py --step 4 --n_rows 8 --kernel_size 3  --src_dir input_1 --output_dir output_1_4_1_8_3_
sbatch --out=slurm/horizon/trial_4_1_8_5__use_centroids.out --err=slurm/horizon/trial_4_1_8_5__use_centroids.err runpymain.sh horizon.py --step 4 --n_rows 8 --kernel_size 5 --use_centroids --src_dir input_1 --output_dir output_1_4_1_8_5__use_centroids
sbatch --out=slurm/horizon/trial_4_1_8_5_.out --err=slurm/horizon/trial_4_1_8_5_.err runpymain.sh horizon.py --step 4 --n_rows 8 --kernel_size 5  --src_dir input_1 --output_dir output_1_4_1_8_5_
sbatch --out=slurm/horizon/trial_4_1_8_7__use_centroids.out --err=slurm/horizon/trial_4_1_8_7__use_centroids.err runpymain.sh horizon.py --step 4 --n_rows 8 --kernel_size 7 --use_centroids --src_dir input_1 --output_dir output_1_4_1_8_7__use_centroids
sbatch --out=slurm/horizon/trial_4_1_8_7_.out --err=slurm/horizon/trial_4_1_8_7_.err runpymain.sh horizon.py --step 4 --n_rows 8 --kernel_size 7  --src_dir input_1 --output_dir output_1_4_1_8_7_
sbatch --out=slurm/horizon/trial_4_2_2_3__use_centroids.out --err=slurm/horizon/trial_4_2_2_3__use_centroids.err runpymain.sh horizon.py --step 4 --n_rows 2 --kernel_size 3 --use_centroids --src_dir input_2 --output_dir output_2_4_2_2_3__use_centroids
sbatch --out=slurm/horizon/trial_4_2_2_3_.out --err=slurm/horizon/trial_4_2_2_3_.err runpymain.sh horizon.py --step 4 --n_rows 2 --kernel_size 3  --src_dir input_2 --output_dir output_2_4_2_2_3_
sbatch --out=slurm/horizon/trial_4_2_2_5__use_centroids.out --err=slurm/horizon/trial_4_2_2_5__use_centroids.err runpymain.sh horizon.py --step 4 --n_rows 2 --kernel_size 5 --use_centroids --src_dir input_2 --output_dir output_2_4_2_2_5__use_centroids
sbatch --out=slurm/horizon/trial_4_2_2_5_.out --err=slurm/horizon/trial_4_2_2_5_.err runpymain.sh horizon.py --step 4 --n_rows 2 --kernel_size 5  --src_dir input_2 --output_dir output_2_4_2_2_5_
sbatch --out=slurm/horizon/trial_4_2_2_7__use_centroids.out --err=slurm/horizon/trial_4_2_2_7__use_centroids.err runpymain.sh horizon.py --step 4 --n_rows 2 --kernel_size 7 --use_centroids --src_dir input_2 --output_dir output_2_4_2_2_7__use_centroids
sbatch --out=slurm/horizon/trial_4_2_2_7_.out --err=slurm/horizon/trial_4_2_2_7_.err runpymain.sh horizon.py --step 4 --n_rows 2 --kernel_size 7  --src_dir input_2 --output_dir output_2_4_2_2_7_
sbatch --out=slurm/horizon/trial_4_2_4_3__use_centroids.out --err=slurm/horizon/trial_4_2_4_3__use_centroids.err runpymain.sh horizon.py --step 4 --n_rows 4 --kernel_size 3 --use_centroids --src_dir input_2 --output_dir output_2_4_2_4_3__use_centroids
sbatch --out=slurm/horizon/trial_4_2_4_3_.out --err=slurm/horizon/trial_4_2_4_3_.err runpymain.sh horizon.py --step 4 --n_rows 4 --kernel_size 3  --src_dir input_2 --output_dir output_2_4_2_4_3_
sbatch --out=slurm/horizon/trial_4_2_4_5__use_centroids.out --err=slurm/horizon/trial_4_2_4_5__use_centroids.err runpymain.sh horizon.py --step 4 --n_rows 4 --kernel_size 5 --use_centroids --src_dir input_2 --output_dir output_2_4_2_4_5__use_centroids
sbatch --out=slurm/horizon/trial_4_2_4_5_.out --err=slurm/horizon/trial_4_2_4_5_.err runpymain.sh horizon.py --step 4 --n_rows 4 --kernel_size 5  --src_dir input_2 --output_dir output_2_4_2_4_5_
sbatch --out=slurm/horizon/trial_4_2_4_7__use_centroids.out --err=slurm/horizon/trial_4_2_4_7__use_centroids.err runpymain.sh horizon.py --step 4 --n_rows 4 --kernel_size 7 --use_centroids --src_dir input_2 --output_dir output_2_4_2_4_7__use_centroids
sbatch --out=slurm/horizon/trial_4_2_4_7_.out --err=slurm/horizon/trial_4_2_4_7_.err runpymain.sh horizon.py --step 4 --n_rows 4 --kernel_size 7  --src_dir input_2 --output_dir output_2_4_2_4_7_
sbatch --out=slurm/horizon/trial_4_2_8_3__use_centroids.out --err=slurm/horizon/trial_4_2_8_3__use_centroids.err runpymain.sh horizon.py --step 4 --n_rows 8 --kernel_size 3 --use_centroids --src_dir input_2 --output_dir output_2_4_2_8_3__use_centroids
sbatch --out=slurm/horizon/trial_4_2_8_3_.out --err=slurm/horizon/trial_4_2_8_3_.err runpymain.sh horizon.py --step 4 --n_rows 8 --kernel_size 3  --src_dir input_2 --output_dir output_2_4_2_8_3_
sbatch --out=slurm/horizon/trial_4_2_8_5__use_centroids.out --err=slurm/horizon/trial_4_2_8_5__use_centroids.err runpymain.sh horizon.py --step 4 --n_rows 8 --kernel_size 5 --use_centroids --src_dir input_2 --output_dir output_2_4_2_8_5__use_centroids
sbatch --out=slurm/horizon/trial_4_2_8_5_.out --err=slurm/horizon/trial_4_2_8_5_.err runpymain.sh horizon.py --step 4 --n_rows 8 --kernel_size 5  --src_dir input_2 --output_dir output_2_4_2_8_5_
sbatch --out=slurm/horizon/trial_4_2_8_7__use_centroids.out --err=slurm/horizon/trial_4_2_8_7__use_centroids.err runpymain.sh horizon.py --step 4 --n_rows 8 --kernel_size 7 --use_centroids --src_dir input_2 --output_dir output_2_4_2_8_7__use_centroids
sbatch --out=slurm/horizon/trial_4_2_8_7_.out --err=slurm/horizon/trial_4_2_8_7_.err runpymain.sh horizon.py --step 4 --n_rows 8 --kernel_size 7  --src_dir input_2 --output_dir output_2_4_2_8_7_
sbatch --out=slurm/horizon/trial_8_1_2_3__use_centroids.out --err=slurm/horizon/trial_8_1_2_3__use_centroids.err runpymain.sh horizon.py --step 8 --n_rows 2 --kernel_size 3 --use_centroids --src_dir input_1 --output_dir output_1_8_1_2_3__use_centroids
sbatch --out=slurm/horizon/trial_8_1_2_3_.out --err=slurm/horizon/trial_8_1_2_3_.err runpymain.sh horizon.py --step 8 --n_rows 2 --kernel_size 3  --src_dir input_1 --output_dir output_1_8_1_2_3_
sbatch --out=slurm/horizon/trial_8_1_2_5__use_centroids.out --err=slurm/horizon/trial_8_1_2_5__use_centroids.err runpymain.sh horizon.py --step 8 --n_rows 2 --kernel_size 5 --use_centroids --src_dir input_1 --output_dir output_1_8_1_2_5__use_centroids
sbatch --out=slurm/horizon/trial_8_1_2_5_.out --err=slurm/horizon/trial_8_1_2_5_.err runpymain.sh horizon.py --step 8 --n_rows 2 --kernel_size 5  --src_dir input_1 --output_dir output_1_8_1_2_5_
sbatch --out=slurm/horizon/trial_8_1_2_7__use_centroids.out --err=slurm/horizon/trial_8_1_2_7__use_centroids.err runpymain.sh horizon.py --step 8 --n_rows 2 --kernel_size 7 --use_centroids --src_dir input_1 --output_dir output_1_8_1_2_7__use_centroids
sbatch --out=slurm/horizon/trial_8_1_2_7_.out --err=slurm/horizon/trial_8_1_2_7_.err runpymain.sh horizon.py --step 8 --n_rows 2 --kernel_size 7  --src_dir input_1 --output_dir output_1_8_1_2_7_
sbatch --out=slurm/horizon/trial_8_1_4_3__use_centroids.out --err=slurm/horizon/trial_8_1_4_3__use_centroids.err runpymain.sh horizon.py --step 8 --n_rows 4 --kernel_size 3 --use_centroids --src_dir input_1 --output_dir output_1_8_1_4_3__use_centroids
sbatch --out=slurm/horizon/trial_8_1_4_3_.out --err=slurm/horizon/trial_8_1_4_3_.err runpymain.sh horizon.py --step 8 --n_rows 4 --kernel_size 3  --src_dir input_1 --output_dir output_1_8_1_4_3_
sbatch --out=slurm/horizon/trial_8_1_4_5__use_centroids.out --err=slurm/horizon/trial_8_1_4_5__use_centroids.err runpymain.sh horizon.py --step 8 --n_rows 4 --kernel_size 5 --use_centroids --src_dir input_1 --output_dir output_1_8_1_4_5__use_centroids
sbatch --out=slurm/horizon/trial_8_1_4_5_.out --err=slurm/horizon/trial_8_1_4_5_.err runpymain.sh horizon.py --step 8 --n_rows 4 --kernel_size 5  --src_dir input_1 --output_dir output_1_8_1_4_5_
sbatch --out=slurm/horizon/trial_8_1_4_7__use_centroids.out --err=slurm/horizon/trial_8_1_4_7__use_centroids.err runpymain.sh horizon.py --step 8 --n_rows 4 --kernel_size 7 --use_centroids --src_dir input_1 --output_dir output_1_8_1_4_7__use_centroids
sbatch --out=slurm/horizon/trial_8_1_4_7_.out --err=slurm/horizon/trial_8_1_4_7_.err runpymain.sh horizon.py --step 8 --n_rows 4 --kernel_size 7  --src_dir input_1 --output_dir output_1_8_1_4_7_
sbatch --out=slurm/horizon/trial_8_1_8_3__use_centroids.out --err=slurm/horizon/trial_8_1_8_3__use_centroids.err runpymain.sh horizon.py --step 8 --n_rows 8 --kernel_size 3 --use_centroids --src_dir input_1 --output_dir output_1_8_1_8_3__use_centroids
sbatch --out=slurm/horizon/trial_8_1_8_3_.out --err=slurm/horizon/trial_8_1_8_3_.err runpymain.sh horizon.py --step 8 --n_rows 8 --kernel_size 3  --src_dir input_1 --output_dir output_1_8_1_8_3_
sbatch --out=slurm/horizon/trial_8_1_8_5__use_centroids.out --err=slurm/horizon/trial_8_1_8_5__use_centroids.err runpymain.sh horizon.py --step 8 --n_rows 8 --kernel_size 5 --use_centroids --src_dir input_1 --output_dir output_1_8_1_8_5__use_centroids
sbatch --out=slurm/horizon/trial_8_1_8_5_.out --err=slurm/horizon/trial_8_1_8_5_.err runpymain.sh horizon.py --step 8 --n_rows 8 --kernel_size 5  --src_dir input_1 --output_dir output_1_8_1_8_5_
sbatch --out=slurm/horizon/trial_8_1_8_7__use_centroids.out --err=slurm/horizon/trial_8_1_8_7__use_centroids.err runpymain.sh horizon.py --step 8 --n_rows 8 --kernel_size 7 --use_centroids --src_dir input_1 --output_dir output_1_8_1_8_7__use_centroids
sbatch --out=slurm/horizon/trial_8_1_8_7_.out --err=slurm/horizon/trial_8_1_8_7_.err runpymain.sh horizon.py --step 8 --n_rows 8 --kernel_size 7  --src_dir input_1 --output_dir output_1_8_1_8_7_
sbatch --out=slurm/horizon/trial_8_2_2_3__use_centroids.out --err=slurm/horizon/trial_8_2_2_3__use_centroids.err runpymain.sh horizon.py --step 8 --n_rows 2 --kernel_size 3 --use_centroids --src_dir input_2 --output_dir output_2_8_2_2_3__use_centroids
sbatch --out=slurm/horizon/trial_8_2_2_3_.out --err=slurm/horizon/trial_8_2_2_3_.err runpymain.sh horizon.py --step 8 --n_rows 2 --kernel_size 3  --src_dir input_2 --output_dir output_2_8_2_2_3_
sbatch --out=slurm/horizon/trial_8_2_2_5__use_centroids.out --err=slurm/horizon/trial_8_2_2_5__use_centroids.err runpymain.sh horizon.py --step 8 --n_rows 2 --kernel_size 5 --use_centroids --src_dir input_2 --output_dir output_2_8_2_2_5__use_centroids
sbatch --out=slurm/horizon/trial_8_2_2_5_.out --err=slurm/horizon/trial_8_2_2_5_.err runpymain.sh horizon.py --step 8 --n_rows 2 --kernel_size 5  --src_dir input_2 --output_dir output_2_8_2_2_5_
sbatch --out=slurm/horizon/trial_8_2_2_7__use_centroids.out --err=slurm/horizon/trial_8_2_2_7__use_centroids.err runpymain.sh horizon.py --step 8 --n_rows 2 --kernel_size 7 --use_centroids --src_dir input_2 --output_dir output_2_8_2_2_7__use_centroids
sbatch --out=slurm/horizon/trial_8_2_2_7_.out --err=slurm/horizon/trial_8_2_2_7_.err runpymain.sh horizon.py --step 8 --n_rows 2 --kernel_size 7  --src_dir input_2 --output_dir output_2_8_2_2_7_
sbatch --out=slurm/horizon/trial_8_2_4_3__use_centroids.out --err=slurm/horizon/trial_8_2_4_3__use_centroids.err runpymain.sh horizon.py --step 8 --n_rows 4 --kernel_size 3 --use_centroids --src_dir input_2 --output_dir output_2_8_2_4_3__use_centroids
sbatch --out=slurm/horizon/trial_8_2_4_3_.out --err=slurm/horizon/trial_8_2_4_3_.err runpymain.sh horizon.py --step 8 --n_rows 4 --kernel_size 3  --src_dir input_2 --output_dir output_2_8_2_4_3_
sbatch --out=slurm/horizon/trial_8_2_4_5__use_centroids.out --err=slurm/horizon/trial_8_2_4_5__use_centroids.err runpymain.sh horizon.py --step 8 --n_rows 4 --kernel_size 5 --use_centroids --src_dir input_2 --output_dir output_2_8_2_4_5__use_centroids
sbatch --out=slurm/horizon/trial_8_2_4_5_.out --err=slurm/horizon/trial_8_2_4_5_.err runpymain.sh horizon.py --step 8 --n_rows 4 --kernel_size 5  --src_dir input_2 --output_dir output_2_8_2_4_5_
sbatch --out=slurm/horizon/trial_8_2_4_7__use_centroids.out --err=slurm/horizon/trial_8_2_4_7__use_centroids.err runpymain.sh horizon.py --step 8 --n_rows 4 --kernel_size 7 --use_centroids --src_dir input_2 --output_dir output_2_8_2_4_7__use_centroids
sbatch --out=slurm/horizon/trial_8_2_4_7_.out --err=slurm/horizon/trial_8_2_4_7_.err runpymain.sh horizon.py --step 8 --n_rows 4 --kernel_size 7  --src_dir input_2 --output_dir output_2_8_2_4_7_
sbatch --out=slurm/horizon/trial_8_2_8_3__use_centroids.out --err=slurm/horizon/trial_8_2_8_3__use_centroids.err runpymain.sh horizon.py --step 8 --n_rows 8 --kernel_size 3 --use_centroids --src_dir input_2 --output_dir output_2_8_2_8_3__use_centroids
sbatch --out=slurm/horizon/trial_8_2_8_3_.out --err=slurm/horizon/trial_8_2_8_3_.err runpymain.sh horizon.py --step 8 --n_rows 8 --kernel_size 3  --src_dir input_2 --output_dir output_2_8_2_8_3_
sbatch --out=slurm/horizon/trial_8_2_8_5__use_centroids.out --err=slurm/horizon/trial_8_2_8_5__use_centroids.err runpymain.sh horizon.py --step 8 --n_rows 8 --kernel_size 5 --use_centroids --src_dir input_2 --output_dir output_2_8_2_8_5__use_centroids
sbatch --out=slurm/horizon/trial_8_2_8_5_.out --err=slurm/horizon/trial_8_2_8_5_.err runpymain.sh horizon.py --step 8 --n_rows 8 --kernel_size 5  --src_dir input_2 --output_dir output_2_8_2_8_5_
sbatch --out=slurm/horizon/trial_8_2_8_7__use_centroids.out --err=slurm/horizon/trial_8_2_8_7__use_centroids.err runpymain.sh horizon.py --step 8 --n_rows 8 --kernel_size 7 --use_centroids --src_dir input_2 --output_dir output_2_8_2_8_7__use_centroids
sbatch --out=slurm/horizon/trial_8_2_8_7_.out --err=slurm/horizon/trial_8_2_8_7_.err runpymain.sh horizon.py --step 8 --n_rows 8 --kernel_size 7  --src_dir input_2 --output_dir output_2_8_2_8_7_
sbatch --out=slurm/horizon/trial_16_1_2_3__use_centroids.out --err=slurm/horizon/trial_16_1_2_3__use_centroids.err runpymain.sh horizon.py --step 16 --n_rows 2 --kernel_size 3 --use_centroids --src_dir input_1 --output_dir output_1_16_1_2_3__use_centroids
sbatch --out=slurm/horizon/trial_16_1_2_3_.out --err=slurm/horizon/trial_16_1_2_3_.err runpymain.sh horizon.py --step 16 --n_rows 2 --kernel_size 3  --src_dir input_1 --output_dir output_1_16_1_2_3_
sbatch --out=slurm/horizon/trial_16_1_2_5__use_centroids.out --err=slurm/horizon/trial_16_1_2_5__use_centroids.err runpymain.sh horizon.py --step 16 --n_rows 2 --kernel_size 5 --use_centroids --src_dir input_1 --output_dir output_1_16_1_2_5__use_centroids
sbatch --out=slurm/horizon/trial_16_1_2_5_.out --err=slurm/horizon/trial_16_1_2_5_.err runpymain.sh horizon.py --step 16 --n_rows 2 --kernel_size 5  --src_dir input_1 --output_dir output_1_16_1_2_5_
sbatch --out=slurm/horizon/trial_16_1_2_7__use_centroids.out --err=slurm/horizon/trial_16_1_2_7__use_centroids.err runpymain.sh horizon.py --step 16 --n_rows 2 --kernel_size 7 --use_centroids --src_dir input_1 --output_dir output_1_16_1_2_7__use_centroids
sbatch --out=slurm/horizon/trial_16_1_2_7_.out --err=slurm/horizon/trial_16_1_2_7_.err runpymain.sh horizon.py --step 16 --n_rows 2 --kernel_size 7  --src_dir input_1 --output_dir output_1_16_1_2_7_
sbatch --out=slurm/horizon/trial_16_1_4_3__use_centroids.out --err=slurm/horizon/trial_16_1_4_3__use_centroids.err runpymain.sh horizon.py --step 16 --n_rows 4 --kernel_size 3 --use_centroids --src_dir input_1 --output_dir output_1_16_1_4_3__use_centroids
sbatch --out=slurm/horizon/trial_16_1_4_3_.out --err=slurm/horizon/trial_16_1_4_3_.err runpymain.sh horizon.py --step 16 --n_rows 4 --kernel_size 3  --src_dir input_1 --output_dir output_1_16_1_4_3_
sbatch --out=slurm/horizon/trial_16_1_4_5__use_centroids.out --err=slurm/horizon/trial_16_1_4_5__use_centroids.err runpymain.sh horizon.py --step 16 --n_rows 4 --kernel_size 5 --use_centroids --src_dir input_1 --output_dir output_1_16_1_4_5__use_centroids
sbatch --out=slurm/horizon/trial_16_1_4_5_.out --err=slurm/horizon/trial_16_1_4_5_.err runpymain.sh horizon.py --step 16 --n_rows 4 --kernel_size 5  --src_dir input_1 --output_dir output_1_16_1_4_5_
sbatch --out=slurm/horizon/trial_16_1_4_7__use_centroids.out --err=slurm/horizon/trial_16_1_4_7__use_centroids.err runpymain.sh horizon.py --step 16 --n_rows 4 --kernel_size 7 --use_centroids --src_dir input_1 --output_dir output_1_16_1_4_7__use_centroids
sbatch --out=slurm/horizon/trial_16_1_4_7_.out --err=slurm/horizon/trial_16_1_4_7_.err runpymain.sh horizon.py --step 16 --n_rows 4 --kernel_size 7  --src_dir input_1 --output_dir output_1_16_1_4_7_
sbatch --out=slurm/horizon/trial_16_1_8_3__use_centroids.out --err=slurm/horizon/trial_16_1_8_3__use_centroids.err runpymain.sh horizon.py --step 16 --n_rows 8 --kernel_size 3 --use_centroids --src_dir input_1 --output_dir output_1_16_1_8_3__use_centroids
sbatch --out=slurm/horizon/trial_16_1_8_3_.out --err=slurm/horizon/trial_16_1_8_3_.err runpymain.sh horizon.py --step 16 --n_rows 8 --kernel_size 3  --src_dir input_1 --output_dir output_1_16_1_8_3_
sbatch --out=slurm/horizon/trial_16_1_8_5__use_centroids.out --err=slurm/horizon/trial_16_1_8_5__use_centroids.err runpymain.sh horizon.py --step 16 --n_rows 8 --kernel_size 5 --use_centroids --src_dir input_1 --output_dir output_1_16_1_8_5__use_centroids
sbatch --out=slurm/horizon/trial_16_1_8_5_.out --err=slurm/horizon/trial_16_1_8_5_.err runpymain.sh horizon.py --step 16 --n_rows 8 --kernel_size 5  --src_dir input_1 --output_dir output_1_16_1_8_5_
sbatch --out=slurm/horizon/trial_16_1_8_7__use_centroids.out --err=slurm/horizon/trial_16_1_8_7__use_centroids.err runpymain.sh horizon.py --step 16 --n_rows 8 --kernel_size 7 --use_centroids --src_dir input_1 --output_dir output_1_16_1_8_7__use_centroids
sbatch --out=slurm/horizon/trial_16_1_8_7_.out --err=slurm/horizon/trial_16_1_8_7_.err runpymain.sh horizon.py --step 16 --n_rows 8 --kernel_size 7  --src_dir input_1 --output_dir output_1_16_1_8_7_
sbatch --out=slurm/horizon/trial_16_2_2_3__use_centroids.out --err=slurm/horizon/trial_16_2_2_3__use_centroids.err runpymain.sh horizon.py --step 16 --n_rows 2 --kernel_size 3 --use_centroids --src_dir input_2 --output_dir output_2_16_2_2_3__use_centroids
sbatch --out=slurm/horizon/trial_16_2_2_3_.out --err=slurm/horizon/trial_16_2_2_3_.err runpymain.sh horizon.py --step 16 --n_rows 2 --kernel_size 3  --src_dir input_2 --output_dir output_2_16_2_2_3_
sbatch --out=slurm/horizon/trial_16_2_2_5__use_centroids.out --err=slurm/horizon/trial_16_2_2_5__use_centroids.err runpymain.sh horizon.py --step 16 --n_rows 2 --kernel_size 5 --use_centroids --src_dir input_2 --output_dir output_2_16_2_2_5__use_centroids
sbatch --out=slurm/horizon/trial_16_2_2_5_.out --err=slurm/horizon/trial_16_2_2_5_.err runpymain.sh horizon.py --step 16 --n_rows 2 --kernel_size 5  --src_dir input_2 --output_dir output_2_16_2_2_5_
sbatch --out=slurm/horizon/trial_16_2_2_7__use_centroids.out --err=slurm/horizon/trial_16_2_2_7__use_centroids.err runpymain.sh horizon.py --step 16 --n_rows 2 --kernel_size 7 --use_centroids --src_dir input_2 --output_dir output_2_16_2_2_7__use_centroids
sbatch --out=slurm/horizon/trial_16_2_2_7_.out --err=slurm/horizon/trial_16_2_2_7_.err runpymain.sh horizon.py --step 16 --n_rows 2 --kernel_size 7  --src_dir input_2 --output_dir output_2_16_2_2_7_
sbatch --out=slurm/horizon/trial_16_2_4_3__use_centroids.out --err=slurm/horizon/trial_16_2_4_3__use_centroids.err runpymain.sh horizon.py --step 16 --n_rows 4 --kernel_size 3 --use_centroids --src_dir input_2 --output_dir output_2_16_2_4_3__use_centroids
sbatch --out=slurm/horizon/trial_16_2_4_3_.out --err=slurm/horizon/trial_16_2_4_3_.err runpymain.sh horizon.py --step 16 --n_rows 4 --kernel_size 3  --src_dir input_2 --output_dir output_2_16_2_4_3_
sbatch --out=slurm/horizon/trial_16_2_4_5__use_centroids.out --err=slurm/horizon/trial_16_2_4_5__use_centroids.err runpymain.sh horizon.py --step 16 --n_rows 4 --kernel_size 5 --use_centroids --src_dir input_2 --output_dir output_2_16_2_4_5__use_centroids
sbatch --out=slurm/horizon/trial_16_2_4_5_.out --err=slurm/horizon/trial_16_2_4_5_.err runpymain.sh horizon.py --step 16 --n_rows 4 --kernel_size 5  --src_dir input_2 --output_dir output_2_16_2_4_5_
sbatch --out=slurm/horizon/trial_16_2_4_7__use_centroids.out --err=slurm/horizon/trial_16_2_4_7__use_centroids.err runpymain.sh horizon.py --step 16 --n_rows 4 --kernel_size 7 --use_centroids --src_dir input_2 --output_dir output_2_16_2_4_7__use_centroids
sbatch --out=slurm/horizon/trial_16_2_4_7_.out --err=slurm/horizon/trial_16_2_4_7_.err runpymain.sh horizon.py --step 16 --n_rows 4 --kernel_size 7  --src_dir input_2 --output_dir output_2_16_2_4_7_
sbatch --out=slurm/horizon/trial_16_2_8_3__use_centroids.out --err=slurm/horizon/trial_16_2_8_3__use_centroids.err runpymain.sh horizon.py --step 16 --n_rows 8 --kernel_size 3 --use_centroids --src_dir input_2 --output_dir output_2_16_2_8_3__use_centroids
sbatch --out=slurm/horizon/trial_16_2_8_3_.out --err=slurm/horizon/trial_16_2_8_3_.err runpymain.sh horizon.py --step 16 --n_rows 8 --kernel_size 3  --src_dir input_2 --output_dir output_2_16_2_8_3_
sbatch --out=slurm/horizon/trial_16_2_8_5__use_centroids.out --err=slurm/horizon/trial_16_2_8_5__use_centroids.err runpymain.sh horizon.py --step 16 --n_rows 8 --kernel_size 5 --use_centroids --src_dir input_2 --output_dir output_2_16_2_8_5__use_centroids
sbatch --out=slurm/horizon/trial_16_2_8_5_.out --err=slurm/horizon/trial_16_2_8_5_.err runpymain.sh horizon.py --step 16 --n_rows 8 --kernel_size 5  --src_dir input_2 --output_dir output_2_16_2_8_5_
sbatch --out=slurm/horizon/trial_16_2_8_7__use_centroids.out --err=slurm/horizon/trial_16_2_8_7__use_centroids.err runpymain.sh horizon.py --step 16 --n_rows 8 --kernel_size 7 --use_centroids --src_dir input_2 --output_dir output_2_16_2_8_7__use_centroids
sbatch --out=slurm/horizon/trial_16_2_8_7_.out --err=slurm/horizon/trial_16_2_8_7_.err runpymain.sh horizon.py --step 16 --n_rows 8 --kernel_size 7  --src_dir input_2 --output_dir output_2_16_2_8_7_
